import { useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import JobExplanationTab from "../components/JobExplanationTab";
import ResumeMatchTab from "../components/ResumeMatchTab";
import TypicalDayTab from "../components/TypicalDayTab";
import {
  createJobDescription,
  generateFullAnalysis,
  uploadResume,
  type JobDescriptionOut,
  type JobExplanation,
  type ResumeMatch,
  type ResumeOut,
  type TypicalDay,
} from "../lib/api";

type Tab = "explanation" | "typical_day" | "resume_match";

export default function JobUnderstanding() {
  const [tab, setTab] = useState<Tab>("explanation");

  const [resumeFile, setResumeFile] = useState<File | null>(null);
  const [resume, setResume] = useState<ResumeOut | null>(null);
  const [resumeError, setResumeError] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);

  const [jdText, setJdText] = useState("");
  const [jobDescription, setJobDescription] = useState<JobDescriptionOut | null>(null);
  const [jdError, setJdError] = useState<string | null>(null);
  const [savingJd, setSavingJd] = useState(false);

  const [explanation, setExplanation] = useState<JobExplanation | null>(null);
  const [translations, setTranslations] = useState<Record<string, JobExplanation>>({});
  const [typicalDay, setTypicalDay] = useState<TypicalDay | null>(null);
  const [match, setMatch] = useState<ResumeMatch | null>(null);

  const [autoGenerating, setAutoGenerating] = useState(false);
  const [autoGenerateError, setAutoGenerateError] = useState<string | null>(null);
  const [autoGeneratedForJobId, setAutoGeneratedForJobId] = useState<string | null>(null);

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    setResumeFile(event.target.files?.[0] ?? null);
  };

  const handleResumeUpload = async (event: FormEvent) => {
    event.preventDefault();
    if (!resumeFile) return;
    setResumeError(null);
    setUploading(true);
    try {
      const result = await uploadResume(resumeFile, resumeFile.name);
      setResume(result);
    } catch (err) {
      setResumeError(err instanceof Error ? err.message : "Upload failed");
    } finally {
      setUploading(false);
    }
  };

  const handleJdSave = async (event: FormEvent) => {
    event.preventDefault();
    if (!jdText.trim()) return;
    setJdError(null);
    setSavingJd(true);
    try {
      const result = await createJobDescription({ raw_text: jdText });
      setJobDescription(result);
      setExplanation(null);
      setTranslations({});
      setTypicalDay(null);
      setMatch(null);
    } catch (err) {
      setJdError(err instanceof Error ? err.message : "Save failed");
    } finally {
      setSavingJd(false);
    }
  };

  // Once both a resume and a job description are available, kick off all three
  // analyses at once (backend runs them concurrently - see app/agents/orchestrator.py)
  // instead of waiting for the user to click "Generate" on each tab individually.
  useEffect(() => {
    if (!resume || !jobDescription) return;
    if (autoGeneratedForJobId === jobDescription.id) return;

    setAutoGeneratedForJobId(jobDescription.id);
    setAutoGenerating(true);
    setAutoGenerateError(null);

    generateFullAnalysis(jobDescription.id, resume.id)
      .then((analysis) => {
        setExplanation(analysis.explanation);
        setTranslations(analysis.translations);
        setTypicalDay(analysis.typical_day);
        setMatch(analysis.match_suggestions);
      })
      .catch((err) => {
        setAutoGenerateError(err instanceof Error ? err.message : "Failed to generate analysis");
      })
      .finally(() => setAutoGenerating(false));
  }, [resume, jobDescription, autoGeneratedForJobId]);

  return (
    <div>
      <div className="page-header">
        <div>
          <h1>Understand a Job</h1>
          <p className="muted">Upload a resume and job description to get started.</p>
        </div>
      </div>

      <div className="split-layout">
        <div className="split-layout-left">
          <div className="card">
            <h2>Resume</h2>
            <form className="form-row" onSubmit={handleResumeUpload}>
              <input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={handleFileChange} />
              <button type="submit" className="btn btn-primary" disabled={!resumeFile || uploading}>
                {uploading ? "Uploading..." : "Upload resume"}
              </button>
            </form>
            {resumeError && <p className="alert">{resumeError}</p>}
            {resume && (
              <div style={{ marginTop: 16 }}>
                <p>
                  Parsed: <strong>{(resume.parsed_json?.full_name as string) ?? resume.label}</strong>
                </p>
                <div className="pill-list">
                  {((resume.parsed_json?.skills as string[]) ?? []).map((skill) => (
                    <span key={skill} className="badge badge-primary">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="card">
            <h2>Job Description</h2>
            <form onSubmit={handleJdSave}>
              <textarea
                className="input"
                rows={8}
                placeholder="Paste the job description here"
                value={jdText}
                onChange={(e) => setJdText(e.target.value)}
              />
              <div style={{ marginTop: 12 }}>
                <button type="submit" className="btn btn-primary" disabled={!jdText.trim() || savingJd}>
                  {savingJd ? "Saving..." : "Save job description"}
                </button>
              </div>
            </form>
            {jdError && <p className="alert">{jdError}</p>}
            {jobDescription && (
              <p className="muted" style={{ marginTop: 10 }}>
                Saved job description ({jobDescription.raw_text.length} chars).
              </p>
            )}
          </div>
        </div>

        <div className="split-layout-right">
          {jobDescription ? (
            <div className="card">
              {autoGenerating && (
                <p className="muted" style={{ marginBottom: 12 }}>
                  Generating explanation, typical day, and resume match at once...
                </p>
              )}
              {autoGenerateError && <p className="alert" style={{ marginBottom: 12 }}>{autoGenerateError}</p>}
              <div className="tabs">
                <button
                  className={"tab-button" + (tab === "explanation" ? " active" : "")}
                  onClick={() => setTab("explanation")}
                >
                  Job Explanation
                </button>
                <button
                  className={"tab-button" + (tab === "typical_day" ? " active" : "")}
                  onClick={() => setTab("typical_day")}
                >
                  Typical Day
                </button>
                <button
                  className={"tab-button" + (tab === "resume_match" ? " active" : "")}
                  onClick={() => setTab("resume_match")}
                >
                  Resume Match
                </button>
              </div>

              {tab === "explanation" && (
                <JobExplanationTab
                  jobId={jobDescription.id}
                  explanation={explanation}
                  translations={translations}
                  onUpdated={(newExplanation, newTranslations) => {
                    setExplanation(newExplanation);
                    setTranslations(newTranslations);
                  }}
                />
              )}
              {tab === "typical_day" && (
                <TypicalDayTab jobId={jobDescription.id} typicalDay={typicalDay} onUpdated={setTypicalDay} />
              )}
              {tab === "resume_match" && (
                <ResumeMatchTab
                  jobId={jobDescription.id}
                  match={match}
                  onUpdated={setMatch}
                  preferredResumeId={resume?.id}
                />
              )}
            </div>
          ) : (
            <div className="card">
              <p className="muted">Save a job description on the left to unlock these tabs.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
